model_spaces:
  xgboost:
    hyperopt_space:
      max_depth: [3, 18]
      gamma: [1, 9]
      reg_alpha: [40, 180]
      reg_lambda: [0, 1]
      colsample_bytree: [0.5, 1]
      min_child_weight: [0, 10]
      n_estimators: 180
      seed: 0
  random_forest:
    hyperopt_space:
      n_estimators: [10, 700]
      max_depth: [1, 100]
      min_samples_split: [2, 20]
      min_samples_leaf: [1, 10]
      max_features: ['sqrt', 'log2']
      random_state: 42
  linear:
    hyperopt_space:
      C: [-4, 4]
      penalty: ['l1', 'l2']
      solver: ['liblinear', 'saga']
      max_iter: [100, 1000]
  fastai_tabular:
    hyperopt_space:
      n_layers: [1, 5]
      layer_size: [32, 1024]
      ps: [0, 0.5]
      bs: [16, 32, 64, 128, 256]
      lr: [1e-5, 1e-1]
      embed_p: [0, 0.5]
